### ISSUE TITLE
Ghidra 10.3 Changed Class - Raising error 'ghidra.program.util.GhidraProgramUtilities' has no attribute 'setAnalyzedFlag'

### ISSUE THREAD

**Issue by clearbluejar** [clearbluejar/ghidrecomp#7]
https://github.com/NationalSecurityAgency/ghidra/blob/303c69ba16a28e594b0ffb6c8c45d41cf3579573/Ghidra/Features/Base/src/main/java/ghidra/program/util/GhidraProgramUtilities.java#L23

`AttributeError: type object 'ghidra.program.util.GhidraProgramUtilities' has no attribute 'setAnalyzedFlag'` in https://github.com/clearbluejar/ghidrecomp/actions/runs/5007536581/jobs/8974271234

**Comment by T-RN-R** [comment]
replace with:                     GhidraProgramUtilities.markProgramAnalyzed(program)
